#pragma once
#include "kxf/UI/Common.h"

#include "kxf/UI/StdIcon.h"
#include "kxf/UI/StdButton.h"
#include "kxf/UI/Validator.h"
#include "kxf/UI/StdDialogButtonSizer.h"
#include "kxf/UI/WindowUpdateLocker.h"
#include "kxf/UI/WindowRefreshScheduler.h"

// Controls
#include "kxf/UI/Controls/AUI.h"
#include "kxf/UI/Controls/DataView.h"

#include "kxf/UI/Controls/BitmapComboBox.h"
#include "kxf/UI/Controls/Button.h"
#include "kxf/UI/Controls/CheckBox.h"
#include "kxf/UI/Controls/ClusterMap.h"
#include "kxf/UI/Controls/ComboBox.h"
#include "kxf/UI/Controls/ComboControl.h"
#include "kxf/UI/Controls/ComboPopup.h"
#include "kxf/UI/Controls/DataViewComboBox.h"
#include "kxf/UI/Controls/HTMLWindow.h"
#include "kxf/UI/Controls/ImageView.h"
#include "kxf/UI/Controls/IProgressMeter.h"
#include "kxf/UI/Controls/Label.h"
#include "kxf/UI/Controls/Notebook.h"
#include "kxf/UI/Controls/ProgressBar.h"
#include "kxf/UI/Controls/RadioButton.h"
#include "kxf/UI/Controls/SearchBox.h"
#include "kxf/UI/Controls/Simplebook.h"
#include "kxf/UI/Controls/Slider.h"
#include "kxf/UI/Controls/StaticBitmap.h"
#include "kxf/UI/Controls/StaticText.h"
#include "kxf/UI/Controls/StatusBar.h"
#include "kxf/UI/Controls/StatusBarEx.h"
#include "kxf/UI/Controls/StyledTextBox.h"
#include "kxf/UI/Controls/TextBox.h"
#include "kxf/UI/Controls/ThumbView.h"
#include "kxf/UI/Controls/WebView.h"

// Dialogs
#include "kxf/UI/Dialogs/Dialog.h"
#include "kxf/UI/Dialogs/StdDialog.h"
#include "kxf/UI/Dialogs/SimpleStdDialog.h"
#include "kxf/UI/Dialogs/ComboBoxDialog.h"
#include "kxf/UI/Dialogs/CredentialsDialog.h"
#include "kxf/UI/Dialogs/FileBrowseDialog.h"
#include "kxf/UI/Dialogs/ProgressDialog.h"
#include "kxf/UI/Dialogs/TaskDialog.h"
#include "kxf/UI/Dialogs/TextBoxDialog.h"

// Menus
#include "kxf/UI/Menus/MenuWidget.h"
#include "kxf/UI/Menus/MenuWidgetItem.h"
#include "kxf/UI/Menus/ShellMenuWidget.h"
#include "kxf/UI/Events/MenuWidgetEvent.h"

// Windows
#include "kxf/UI/Windows/Frame.h"
#include "kxf/UI/Windows/Panel.h"
#include "kxf/UI/Windows/TopLevelWindow.h"
#include "kxf/UI/Windows/CollapsiblePane.h"
#include "kxf/UI/Windows/DrawablePanel.h"
#include "kxf/UI/Windows/RichToolTip.h"
#include "kxf/UI/Windows/SplashWindow.h"
#include "kxf/UI/Windows/SplitterWindow.h"
#include "kxf/UI/Windows/ToolTipEx.h"
