set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)

if(PORT STREQUAL "Sciter" OR PORT STREQUAL "kxvfs")
    set(VCPKG_LIBRARY_LINKAGE dynamic)
endif()
