#include "KxStdAfx.h"
#include "KxFramework/KxDataView2Event.h"

namespace KxDataView2
{
	wxDEFINE_EVENT(EVENT_ITEM_SELECTED, Event);
	wxDEFINE_EVENT(EVENT_ITEM_HOVERED, Event);
	wxDEFINE_EVENT(EVENT_ITEM_ACTIVATED, Event);
	wxDEFINE_EVENT(EVENT_ITEM_COLLAPSED, Event);
	wxDEFINE_EVENT(EVENT_ITEM_EXPANDED, Event);
	wxDEFINE_EVENT(EVENT_ITEM_COLLAPSING, Event);
	wxDEFINE_EVENT(EVENT_ITEM_EXPANDING, Event);
	wxDEFINE_EVENT(EVENT_ITEM_CONTEXT_MENU, Event);
	wxDEFINE_EVENT(EVENT_ITEM_VALUE_CHANGED, Event);

	wxDEFINE_EVENT(EVENT_COLUMN_HEADER_CLICK, Event);
	wxDEFINE_EVENT(EVENT_COLUMN_HEADER_RCLICK, Event);
	wxDEFINE_EVENT(EVENT_COLUMN_SORTED, Event);
	wxDEFINE_EVENT(EVENT_COLUMN_MOVED, Event);
	wxDEFINE_EVENT(EVENT_VIEW_CACHE_HINT, Event);

	wxDEFINE_EVENT(KxEVT_DATAVIEW_ITEM_EDIT_ATTACH, EditorEvent);
	wxDEFINE_EVENT(KxEVT_DATAVIEW_ITEM_EDIT_DETACH, EditorEvent);
	wxDEFINE_EVENT(EVENT_ITEM_EDIT_STARTING, EditorEvent);
	wxDEFINE_EVENT(EVENT_ITEM_EDIT_STARTED, EditorEvent);
	wxDEFINE_EVENT(EVENT_ITEM_EDIT_DONE, EditorEvent);

	wxDEFINE_EVENT(EVENT_ITEM_DRAG, EventDND);
	wxDEFINE_EVENT(EVENT_ITEM_DROP_POSSIBLE, EventDND);
	wxDEFINE_EVENT(EVENT_ITEM_DROP, EventDND);
}
