#undef GetObject
#undef min
#undef max
#undef SetCurrentDirectory
#undef CopyFile
#undef MoveFile
#undef DeleteFile
#undef GetBinaryType
#undef MessageBox
#undef GetFreeSpace
#undef PlaySound
#undef RegisterClass
#undef CreateEvent
#undef GetFirstChild
#undef GetNextSibling
#undef GetPrevSibling
#undef GetWindowStyle
#undef GetLongPathName
#undef GetFullPathName
#undef EnumResourceTypes
#undef LoadImage
#undef UpdateResource
#undef BeginUpdateResource
#undef EndUpdateResource
#undef EnumResourceLanguages
#undef FormatMessage
#undef GetCommandLine
#undef CreateProcess
#undef EnumProcesses
#undef GetUserName
#undef FindFirstFile
#undef FindNextFile
#undef GetEnvironmentVariable
#undef SetEnvironmentVariable
